// frontend/src/procurement/ProductList.tsx
import { Button, Card, Image, List, message, Space, Tag, Typography } from "antd";
import { useState } from "react";

import type { ProductView, ProductsEventValue } from "../schemas/procurementEvents";
import type { PurchaseFormBridge } from "./PurchaseFormBridge";

interface ProductListProps {
  payload: ProductsEventValue["payload"];
  bridge: PurchaseFormBridge;
  onProductAdded: (product: ProductView) => void;
}

/** 展示搜索服务已经排序的商品；组件不重排，也不向 Agent 提交“加购”。 */
export function ProductList({ payload, bridge, onProductAdded }: ProductListProps) {
  const [addingProductId, setAddingProductId] = useState<string | null>(null);
  const [messageApi, messageContext] = message.useMessage();

  const addProduct = async (product: ProductView) => {
    setAddingProductId(product.productId);
    try {
      const result = await bridge.addProduct(product);
      if (result.success) {
        onProductAdded(product);
        void messageApi.success(result.message);
      } else {
        void messageApi.error(result.message);
      }
    } catch {
      void messageApi.error("加购失败，商品和推荐操作均已保留，请重试");
    } finally {
      setAddingProductId(null);
    }
  };

  return (
    <section aria-label="推荐商品" className="assistant-block">
      {messageContext}
      <Space align="baseline">
        <Typography.Title level={4}>{payload.title}</Typography.Title>
        <Typography.Text type="secondary">第 {payload.page} 批</Typography.Text>
      </Space>
      <List
        grid={{ gutter: 16, column: 3 }}
        dataSource={payload.products}
        renderItem={(product) => (
          <List.Item key={product.productId}>
            <Card
              className="product-card"
              cover={
                product.imageUrl ? (
                  <Image src={product.imageUrl} alt={product.name} height={160} preview={false} />
                ) : (
                  <div className="product-placeholder" aria-hidden="true">
                    商品图片
                  </div>
                )
              }
              actions={[
                <Button
                  key="add"
                  type="primary"
                  loading={addingProductId === product.productId}
                  onClick={() => void addProduct(product)}
                >
                  加购
                </Button>,
              ]}
            >
              <Card.Meta
                title={product.name}
                description={
                  <Space direction="vertical" size={6}>
                    <Typography.Text strong>
                      {product.price === null
                        ? "价格待确认"
                        : `${product.currency ?? ""} ${product.price.toLocaleString()}`}
                    </Typography.Text>
                    {product.deliveryText && (
                      <Typography.Text type="secondary">{product.deliveryText}</Typography.Text>
                    )}
                    <Space size={[4, 4]} wrap>
                      {product.badges.map((badge) => (
                        <Tag key={badge}>{badge}</Tag>
                      ))}
                    </Space>
                  </Space>
                }
              />
            </Card>
          </List.Item>
        )}
      />
    </section>
  );
}

// frontend/src/procurement/ProductList.vue
<script setup lang="ts">
import { ref } from "vue";

import type { ProductView, ProductsEventValue } from "../schemas/procurementEvents";
import type { PurchaseFormBridge } from "./PurchaseFormBridge";

const props = defineProps<{
  payload: ProductsEventValue["payload"];
  bridge: PurchaseFormBridge;
}>();

const emit = defineEmits<{
  productAdded: [product: ProductView];
}>();

const addingProductId = ref<string | null>(null);
const notice = ref<{ type: "success" | "error"; text: string } | null>(null);

function formatPrice(product: ProductView): string {
  return product.price === null
    ? "价格待确认"
    : `${product.currency ?? ""} ${product.price.toLocaleString()}`.trim();
}

async function addProduct(product: ProductView): Promise<void> {
  addingProductId.value = product.productId;
  notice.value = null;
  try {
    const result = await props.bridge.addProduct(product);
    notice.value = { type: result.success ? "success" : "error", text: result.message };
    if (result.success) {
      emit("productAdded", product);
    }
  } catch {
    notice.value = { type: "error", text: "加购失败，商品和推荐操作均已保留，请重试" };
  } finally {
    addingProductId.value = null;
  }
}
</script>

<template>
  <section aria-label="推荐商品" class="assistant-block product-section">
    <div class="section-heading">
      <h2>{{ payload.title }}</h2>
      <span class="secondary-text">第 {{ payload.page }} 批</span>
    </div>
    <a-alert
      v-if="notice"
      class="product-notice"
      :type="notice.type"
      :message="notice.text"
      show-icon
    />
    <div class="product-grid">
      <article v-for="product in payload.products" :key="product.productId" class="product-card">
        <img v-if="product.imageUrl" :src="product.imageUrl" :alt="product.name" />
        <div v-else class="product-placeholder" aria-hidden="true">商品图片</div>
        <div class="product-body">
          <h3>{{ product.name }}</h3>
          <strong>{{ formatPrice(product) }}</strong>
          <span v-if="product.deliveryText" class="secondary-text">{{ product.deliveryText }}</span>
          <div class="tag-row">
            <a-tag v-for="badge in product.badges" :key="badge">
              {{ badge }}
            </a-tag>
          </div>
          <a-button
            type="primary"
            block
            :loading="addingProductId === product.productId"
            @click="void addProduct(product)"
          >
            加购
          </a-button>
        </div>
      </article>
    </div>
  </section>
</template>
