// frontend/src/procurement/QueueNotice.vue
<script setup lang="ts">
import type { QueueEventValue } from "../schemas/procurementEvents";

defineProps<{
  payload: QueueEventValue["payload"];
}>();
</script>

<template>
  <!-- 排队文本由后端固定生成，前端只按普通文本展示。 -->
  <a-alert type="info" show-icon :message="payload.text" class="assistant-block" />
</template>

// frontend/src/procurement/QueueNotice.tsx
import { Alert } from "antd";

import type { QueueEventValue } from "../schemas/procurementEvents";

/** 排队文案由后端固定生成，前端只按普通文本展示。 */
export function QueueNotice({ payload }: { payload: QueueEventValue["payload"] }) {
  return <Alert type="info" showIcon message={payload.text} className="assistant-block" />;
}
