// frontend/src/assistant/ActionBar.tsx
import { Button, Card, Space } from "antd";

import type { ActionsEventValue } from "../schemas/procurementEvents";

interface ActionBarProps {
  payload: ActionsEventValue["payload"];
  disabled: boolean;
  onAction: (actionId: string) => void;
}

/** 后端签发的一组一次性 Action；提交任一项时整组进入禁用状态。 */
export function ActionBar({ payload, disabled, onAction }: ActionBarProps) {
  return (
    <Card title={payload.title} className="assistant-block">
      <Space wrap>
        {payload.actions.map((action) => (
          <Button
            key={action.actionId}
            type={action.style === "primary" ? "primary" : "default"}
            danger={action.style === "danger"}
            disabled={disabled}
            loading={disabled}
            onClick={() => onAction(action.actionId)}
          >
            {action.label}
          </Button>
        ))}
      </Space>
    </Card>
  );
}

// frontend/src/assistant/ActionBar.vue
<script setup lang="ts">
import type { ActionsEventValue } from "../schemas/procurementEvents";

defineProps<{
  payload: ActionsEventValue["payload"];
  disabled: boolean;
}>();

const emit = defineEmits<{
  action: [actionId: string];
}>();
</script>

<template>
  <a-card :title="payload.title" class="assistant-block">
    <div class="button-row">
      <a-button
        v-for="action in payload.actions"
        :key="action.actionId"
        :type="action.style === 'primary' ? 'primary' : 'default'"
        :danger="action.style === 'danger'"
        :disabled="disabled"
        :loading="disabled"
        @click="emit('action', action.actionId)"
      >
        {{ action.label }}
      </a-button>
    </div>
  </a-card>
</template>
