// frontend/src/assistant/MessageList.tsx
import { Empty, List, Typography } from "antd";

import type { DisplayMessage } from "../agui/eventReducer";

/** 助手文字始终按纯文本渲染，禁止 HTML 注入。 */
export function MessageList({ messages }: { messages: DisplayMessage[] }) {
  if (messages.length === 0) {
    return <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="还没有消息" />;
  }
  return (
    <List
      className="message-list"
      dataSource={messages}
      renderItem={(message) => (
        <List.Item key={message.id} className={`message-row message-${message.role}`}>
          <div className="message-bubble" aria-live={message.streaming ? "polite" : "off"}>
            <Typography.Text>{message.content || "…"}</Typography.Text>
          </div>
        </List.Item>
      )}
    />
  );
}

// frontend/src/assistant/MessageList.vue
<script setup lang="ts">
import type { DisplayMessage } from "../agui/eventReducer";

defineProps<{
  messages: DisplayMessage[];
}>();
</script>

<template>
  <div v-if="messages.length === 0" class="empty-state">还没有消息</div>
  <ul v-else class="message-list" aria-live="polite">
    <li
      v-for="message in messages"
      :key="message.id"
      class="message-row"
      :class="`message-${message.role}`"
    >
      <span class="message-bubble">{{ message.content || "…" }}</span>
    </li>
  </ul>
</template>
