// frontend/src/assistant/SceneEntrances.tsx
import { Button, Card, Space, Typography } from "antd";

interface SceneEntrancesProps {
  disabled: boolean;
  onTrigger: (scenarioId: "smart_routing" | "knowledge_recommendation") => void;
}

/** 只在没有活动 DAG 时显示两个准确场景入口。 */
export function SceneEntrances({ disabled, onTrigger }: SceneEntrancesProps) {
  return (
    <Card className="scene-entrances">
      <Typography.Title level={4}>选择一个场景开始</Typography.Title>
      <Space wrap>
        <Button type="primary" disabled={disabled} onClick={() => onTrigger("smart_routing")}>
          智能分流
        </Button>
        <Button disabled={disabled} onClick={() => onTrigger("knowledge_recommendation")}>
          知识推荐
        </Button>
      </Space>
    </Card>
  );
}

// frontend/src/assistant/SceneEntrances.vue
<script setup lang="ts">
defineProps<{
  disabled: boolean;
}>();

const emit = defineEmits<{
  trigger: [scenarioId: "smart_routing" | "knowledge_recommendation"];
}>();
</script>

<template>
  <a-card class="scene-entrances">
    <h2>选择一个场景开始</h2>
    <div class="button-row">
      <a-button type="primary" :disabled="disabled" @click="emit('trigger', 'smart_routing')">
        智能分流
      </a-button>
      <a-button :disabled="disabled" @click="emit('trigger', 'knowledge_recommendation')">
        知识推荐
      </a-button>
    </div>
  </a-card>
</template>
